### ISSUE TITLE
Issue running from pre-commit sets is_print_mode=True

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#65] opened 2020-01-02 15:08 UTC
Hi again,

I updated everything to the latest version to take advantage of the latest fixes and get the following issue. When i run:

`importanize src/Packages/sqlite/pysqlite2/test/__init__.py -vv --config=setup.cfg`

i get the following:

```
$ importanize src/Packages/sqlite/pysqlite2/test/__init__.py -vv --config=setup.cfg
Running importanize with RuntimeConfig(_paths=(), path_names=('src/Packages/sqlite/pysqlite2/test/__init__.py',), formatter_name=None, length=None, should_add_last_line=True, _config=None, root_config=[importanize]
path=setup.cfg
after_imports_new_lines=1
length=120
formatter=lines
groups=
  stdlib
  sitepackages
  remainder
  local
  packages:db,gui
exclude=
  *launcher\requirements*
add_imports=
allow_plugins=False
plugins=
  unused_imports, config_path='setup.cfg', is_subconfig_allowed=True, are_plugins_allowed=None, should_deactivate_piped_plugins=None, found_configs={}, verbosity=2, is_version_mode=False, is_list_mode=False, is_ci_mode=False, show_diff=False, is_print_mode=False, show_header=True, is_in_piped=False, is_out_piped=False, stdin=<_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>, stdout=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>)
Running with python c:\users\user\appdata\local\programs\python\python38-32\python.exe
Installed plugins: separate_libs, unused_imports
About to importanize src\Packages\sqlite\pysqlite2\test\__init__.py
Found 9 imports in src\Packages\sqlite\pysqlite2\test\__init__.py
Successfully importanized src\Packages\sqlite\pysqlite2\test\__init__.py
Nothing to do src\Packages\sqlite\pysqlite2\test\__init__.py
```

This is as should be.

When i run pre-commit with the one file i get this:

```
$ pre-commit run importanize
[WARNING] Unstaged files detected.
importanize..............................................................Failed
- hook id: importanize
- exit code: 1

Running importanize with RuntimeConfig(_paths=(), path_names=('src/Packages/sqlite/pysqlite2/test/__init__.py',), formatter_name=None, length=None, should_add_last_line=True, _config=None, root_config=[importanize]
path=setup.cfg
after_imports_new_lines=1
length=120
formatter=lines
groups=
  stdlib
  sitepackages
  remainder
  local
  packages:db,gui
exclude=
  *launcher\requirements*
add_imports=
allow_plugins=False
plugins=
  unused_imports, config_path='setup.cfg', is_subconfig_allowed=True, are_plugins_allowed=None, should_deactivate_piped_plugins=None, found_configs={}, verbosity=2, is_version_mode=False, is_list_mode=False, is_ci_mode=False, show_diff=False, is_print_mode=True, show_header=True, is_in_piped=True, is_out_piped=True, stdin=<_io.TextIOWrapper name='<stdin>' mode='r' encoding='cp1255'>, stdout=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1255'>)
Running with python c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\scripts\python.exe
Installed plugins: separate_libs, unused_imports
About to importanize src\Packages\sqlite\pysqlite2\test\__init__.py
Found 9 imports in src\Packages\sqlite\pysqlite2\test\__init__.py
Successfully importanized src\Packages\sqlite\pysqlite2\test\__init__.py
==============================================
src\Packages\sqlite\pysqlite2\test\__init__.py
==============================================
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\Lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\Scripts\importanize.exe\__main__.py", line 7, in <module>
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\importanize\main.py", line 174, in cli
    main(
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\importanize\main.py", line 227, in main
    return runtime_config.aggregator()
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\importanize\importanize.py", line 376, in __call__
    self.update(result)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\importanize\importanize.py", line 452, in update
    click.echo(result.organized, file=self.runtime_config.stdout)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\site-packages\click\utils.py", line 260, in echo
    file.write(message)
  File "c:\users\user\.cache\pre-commit\repo1c2ulo2f\py_env-python3\lib\encodings\cp1255.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe4' in position 133: character maps to <undefined>

[INFO] Restored changes from C:\Users\user/.cache\pre-commit\patch1577976846.
```

I'll draw attention to the following differences:
```
is_print_mode=False
is_in_piped=False,
is_out_piped=False
stdin/out has encoding encoding='utf-8'.
```

I am running in cygwin in both examples, but even if i run from cmd it gets utf8 as its encoding when run directly.

Is the difference (printing and different encoding) because of the way pre-commit runs importanize or due to some issue with click?

**Comment by miki725** [comment] 2020-01-05 02:45
as far as I know in pre-commit it should should not be in print mode, at least its not for me. I did change in 0.8 to be or current master how pipes work https://github.com/miki725/importanize/#pipe-support but havent tested on Windows. probably will need to test in a vm. in the worst case for windows users will provide a `--no-pipe` flag or something similar to disable auto pipe detection in case cygwin does something strange.

**Comment by commentator8** [comment] 2020-01-05 08:19
Thanks, will wait and test when you have added.

**Comment by miki725** [comment] 2020-01-05 17:47
just tried in a vm and it works as expected with pre-commit:

![image](https://user-images.githubusercontent.com/932940/71783759-5a614200-2fb9-11ea-8ab5-d2714df2ab50.png)

print mode is not enabled. tested on vanilla win10 VM with cygwin + python3.6 installed since cygwin did not have anything newer by default. not sure how to replicate your report.

**Comment by miki725** [comment] 2020-01-06 02:19
https://github.com/miki725/importanize/pull/68 adds `--no-auto-pipe` option. Hopefully it helps in you case since I cant reproduce. When Ill merge the PR it will auto-close this ticket but feel free to reopen if you have any issues. Also thanks for all the reports! Really appreciate someone using and helping to make importanize better 🎉

**Closed** 2020-01-06 02:28 UTC
