### ISSUE TITLE
conflict with yapf on lines after imports

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#69] opened 2020-01-20 10:27 UTC
Hi,

When i run importanize and yapf together with pre-commit i get the following circular fix issue:
importanize changes the following code to have only one line after the import (when setting `after_imports_new_lines=1` to achieve compatibility with yapf's 1 line style) as you would expect but yapf also considers (as pep8 does to the best of my knowledge) that before classes/functions there should be 2 lines. So yapf would leave this 2 lines while importanize changes it to 1.

Any possibility of adding a flag that allows for lines before class (that overrides after imports)?

```
import requests


def a():
```

**Comment by miki725** [comment] 2020-01-20 16:03
Hmm. The problem is that if imports are not organized and importanize does not limit to specific number of new lines, sometimes end result is more than 2 blank lines. I guess it would be possible to detect classes but another option is to simply not enforce any number of new lines and let something else lint that. In your case yapf then can detect many lines and complain but otherwise that can avoid any potential conflicts with other lint rules. Thoughts?

**Comment by commentator8** [comment] 2020-01-20 17:36
Opt out sounds good to me. Thanks for the quick responses..

**Comment by miki725** [comment] 2020-01-21 14:15
https://github.com/miki725/importanize/pull/70 adds an option to skip adding new lines. its not complete but if you can give that branch a test drive that could help to test that your yapf config plays nice now

**Comment by miki725** [comment] 2020-01-22 14:43
merged recently so will close this issue. feel free to reopen if you have more issues

**Closed by miki725** 2020-01-22 14:43 UTC

**Comment by commentator8** [comment] 2020-01-26 14:40
Will check - was on vacation, sorry.
