### ISSUE TITLE
Feature: Ignore specific lines in file

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#72] opened 2020-02-05 07:05 UTC
I have a use case where i would like importanize (ideally) to run on a file but ignore a specific region. I can of course exclude the file, but that is not the goal.

if i have for example a os.environ or sys.path call where i add something needed for the import after it i would like to surround it with #importanize off and #importanize on or the like.

Something like [this](https://github.com/timothycrosley/isort#skip-processing-of-imports-outside-of-configuration) but with multiline support (unless i just comment the sys.path and import and it ignores them).

What do you think?

**Comment by miki725** [comment] 2020-02-07 14:26
duplicate of https://github.com/miki725/importanize/issues/18


although I usually use the if statement:

```python
import sys
sys.path.insert(0, '...')

if True:
    # not importanized imports
    import itertools
```

**Closed** 2020-02-07 14:27 UTC

**Comment by commentator8** [comment] 2020-02-08 17:55
Ok i guess i will just exclude the file from importanize - i cant see my team accepting if True as a solution sadly. Thanks anyway.
